import math;
p = int(input("Enter  p: "))
q = int(input("Enter  q: "))
n = p * q
print("n : ",n)
phi_n = (p - 1) * (q - 1)
print("phin_n :",phi_n)
e =int(input("Enter e : "))
m=int(input("Enter m :"))
d=pow(e,-1,phi_n)
print("d is :",d)
print(f"Public Key (e,n): {e,n}")
print(f"Private Key (d,n): {d,n}")
C=pow(m,e,n)
print("C is :",C)
M=pow(C,d,n)
print("M is :",M)
